[package]
name = "stdout-tv"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
ctrlc = "3.5.1"
image = "0.25.9"
pixel2ascii = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
